-- =====================================================================
-- 삼일한끼 Supabase 설정 (3) — 서버 자동 매칭(Vercel Cron) 허용 + 조원 순서 보정
-- 01_schema.sql을 이미 실행한 프로젝트에서만 이 파일을 실행하세요.
-- (01_schema.sql을 처음 실행하는 경우에는 이 내용이 이미 들어 있어서 필요 없어요)
-- SQL Editor > New query 에 전체를 붙여 넣고 [Run]. 여러 번 실행해도 안전합니다.
-- =====================================================================

-- 조원 순서를 정확히 기록하는 순번 칸 (같은 순간에 저장돼도 순서 유지)
alter table public.group_members add column if not exists seq bigint generated by default as identity;

-- 내 결과: 이메일 + 코드가 맞을 때만 "내 정보 + 내 조"만 돌려줌 (전체 목록은 절대 안 내려감)
create or replace function public.get_my_result(p_email text, p_code text)
returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v          jsonb;
  a          public.applications;
  g          public.groups;
  v_members  jsonb;
  v_depts    int;
begin
  v := public._verify_applicant(p_email, p_code);
  if v->>'status' <> 'ok' then
    return jsonb_build_object('ok', false, 'locked', v->>'status' = 'locked');
  end if;

  select * into a from public.applications where id = (v->>'id')::uuid;
  select gr.* into g from public.groups gr
    join public.group_members gm on gm.group_id = gr.id
   where gm.application_id = a.id;

  if g.id is not null then
    select jsonb_agg(jsonb_build_object(
             'id', m.id,
             'name', m.name,
             'email', m.email,
             'deptOpen', m.dept_open,
             'dept', case when m.dept_open then m.dept else '' end,
             'interests', to_jsonb(m.interests),
             'favoriteThing', m.favorite_thing,
             'response', gm.response
           ) order by gm.seq),
           count(distinct m.dept)
      into v_members, v_depts
      from public.group_members gm
      join public.applications m on m.id = gm.application_id
     where gm.group_id = g.id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'me', jsonb_build_object('id', a.id, 'name', a.name, 'email', a.email,
                             'slots', to_jsonb(a.slots), 'createdAt', a.created_at),
    'group', case when g.id is null then null else jsonb_build_object(
               'id', g.id, 'no', g.no, 'slot', g.slot, 'locked', g.locked,
               'deptCount', v_depts, 'members', v_members) end
  );
end;
$$;

-- 매칭 결과 저장: 새 조(조 번호는 여기서 이어서 발급) + 기존 조 합류 + 실행 기록
-- 운영자 콘솔(로그인한 운영자) 또는 서버 자동 매칭(Vercel Cron, secret key = service_role)만 실행 가능
create or replace function public.admin_save_matching(
  p_groups jsonb, p_joins jsonb, p_summary text, p_auto boolean default false)
returns int
language plpgsql security definer set search_path = ''
as $$
declare
  v_no   int;
  v_new  int := 0;
  g      jsonb;
  j      jsonb;
  v_gid  uuid;
begin
  if not (public.is_admin()
          or coalesce(nullif(current_setting('request.jwt.claims', true), ''), '{}')::jsonb ->> 'role' = 'service_role') then
    raise exception '운영자만 실행할 수 있어요.';
  end if;
  select next_no into v_no from public.settings where id = 1 for update;

  for g in select * from jsonb_array_elements(coalesce(p_groups, '[]'::jsonb)) loop
    insert into public.groups (no, slot) values (v_no, g->>'slot') returning id into v_gid;
    v_no := v_no + 1;
    v_new := v_new + 1;
    insert into public.group_members (group_id, application_id)
      select v_gid, t.x::uuid
        from jsonb_array_elements_text(g->'memberIds') with ordinality as t(x, i)
       order by t.i;
  end loop;

  for j in select * from jsonb_array_elements(coalesce(p_joins, '[]'::jsonb)) loop
    insert into public.group_members (group_id, application_id)
      values ((j->>'groupId')::uuid, (j->>'memberId')::uuid);
  end loop;

  update public.settings set
    next_no = v_no,
    last_run_at = now(),
    last_auto_run_at = case when p_auto then now() else last_auto_run_at end,
    last_run_summary = coalesce(p_summary, '')
  where id = 1;
  return v_new;
end;
$$;

grant execute on function public.is_admin(), public.admin_save_matching(jsonb, jsonb, text, boolean) to service_role;
